- JOB: "intercept -g $DEVNODE | dual-function-keys -c /etc/interception/dual-function-keys/interception_mappings.yaml | uinput -d $DEVNODE"
  DEVICE:
    NAME: "Logitech USB Receiver"
    EVENTS:
      EV_KEY: [ KEY_LEFTCTRL ]
